"""add created_at to atletas

Revision ID: 63ad92c3420a
Revises: 3cf377947327
Create Date: 2025-08-15 16:19:27.626013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ad92c3420a'
down_revision: Union[str, Sequence[str], None] = '3cf377947327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('atletas', 'data_registro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('data_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('atletas', 'created_at')
    # ### end Alembic commands ###
